### ISSUE TITLE
URL in get param has /, which makes it not work

### ISSUE THREAD

**Issue by ayushsubedi** [Traitor00/youtube_video_downloader#1]
The problem is that your youtube URL also has / which flask confuses for its own path. Here is a solution 

```python
from flask import Flask
from pytube import Playlist

app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"

@app.route("/playlist/<playlist>/")
def download_playlist(playlist):
    playlist = "https://www.youtube.com/playlist?list="+playlist
    p = Playlist(playlist)
    for video in p.videos:
        video.streams.first().download()
```

**Comment by himal-rawal** [comment]
wow,Thanks Sir  it worked. I never thought of doing that  instead i was thnking of changing request method from get to post and sending parameter through request's body instead of url. As you have mentioned I changed this `  p = Playlist("https://www.youtube.com/playlist?list="+playlistid)` and It worked. Thanks
